FROM debian:stable-slim

COPY ./nginx.conf /etc/nginx/conf.d

RUN apt-get update -y \
    && apt-get install -y \
        nginx \
        openssl \
    && mkdir /etc/nginx/ssl \
    && openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes \
            -out /etc/nginx/ssl/lzipp.crt \
            -keyout /etc/nginx/ssl/lzipp.key \
    && mkdir -p /run/nginx

CMD ["nginx", "-g", "daemon off;"]