volumes:
    # wordpress:
    mariadb:

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./dockerfiles/nginx/.
        ports:
            - "80:80"
        depends_on:
            - wordpress
        volumes:
            - ./web:/var/www/html
        networks:
            - inception
        # env_file:
        #     - .env
        restart: always
    wordpress:
        container_name: wordpress
        build: ./dockerfiles/wordpress/.
        depends_on:
            - mariadb
        volumes:
            - ./web:/var/www/html
        networks:
            - inception
        # env_file:
        #     - .env
        restart: always
    mariadb:
        container_name: mariadb
        build: ./dockerfiles/mariadb/.
        volumes:
            - mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception
        restart: always
