volumes:
    wordpress_database:
        driver: local
    wordpress_website_files:
        driver: local

networks:
    inception:
        name: inception

services:
    nginx:
        container_name: nginx
        build: ./dockerfiles/nginx/.
        ports:
            - "443:443"
            # - "80:80" # explicitly not used
        depends_on:
            - wordpress
        volumes:
            - ./web:/var/www/html
        networks:
            - inception
        # env_file:
        #     - .env
        restart: always
    wordpress:
        container_name: wordpress
        build: ./dockerfiles/wordpress/.
        depends_on:
            - mariadb
        volumes:
            - ./web:/var/www/html
        networks:
            - inception
        secrets:
            - wp_admin
            - wp_admin_email
            - wp_admin_pwd
            - wp_email
            - wp_pwd
            - wp_title
            - wp_user
        restart: always
    mariadb:
        container_name: mariadb
        build: ./dockerfiles/mariadb/.
        volumes:
            - mariadb:/var/lib/mysql
            - /home/lzipp/data/mariadb:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception
        restart: always
