volumes:
    wordpress_database:
        driver: local
    wordpress_website_files:
        driver: local

networks:
    inception:
        name: inception

secrets:
    db_wp_name:
        file: secrets/db_wp_name.txt
    db_wp_pwd:
        file: srcs/secrets/db_wp_pwd.txt
    db_wp_user:
        file: secrets/db_wp_user.txt

services:
#    nginx:
#        container_name: nginx
#        build: ./dockerfiles/nginx/.
#        ports:
#            - "443:443"
#            # - "80:80" # explicitly not used
#        depends_on:
#            - wordpress
#        volumes:
#            - ./web:/var/www/html
#        networks:
#            - inception
#        restart: always
#    wordpress:
#        container_name: wordpress
#        build: ./dockerfiles/wordpress/.
#        ports:
#            - "9000:9000"
#        depends_on:
#            - mariadb
#        volumes:
#            - ./web:/var/www/html
#        networks:
#            - inception
#        secrets:
#            - wp_admin
#            - wp_admin_email
#            - wp_admin_pwd
#            - wp_email
#            - wp_pwd
#            - wp_title
#            - wp_user
#        restart: always
    db:
        container_name: db
        build:
            context: srcs/dockerfiles/mariadb
            target: base
        ports:
            - "3306:3306"
        volumes:
#            - mariadb:/var/lib/mysql
#            - /home/lzipp/data/mariadb:/var/lib/mysql
            - /var/lib/mysql
        secrets:
            - db_wp_pwd
        environment:
            - DB_WP_USER=${DB_WP_USER}
            - DB_WP_NAME=${DB_WP_NAME}
        networks:
            - inception
        restart: unless-stopped
        user:
            mysql
